### ISSUE TITLE
Returned LCP license can still be opened

### ISSUE THREAD

**Issue by olivierkorner** [readium/r2-lcp-swift#116]
Some LCP servers don't update the `rights.end` date in the LCP license document when the license is returned.
As a consequence, you can still decrypt the license and open the publication even though the license is no longer valid.

This is happening because R2 LCP code doesn't check the status document if the rights.end date is in the future.
https://github.com/readium/r2-lcp-swift/blob/4b4debc40d9a11a52874e11ed63bd936f4bec1ed/readium-lcp-swift/License/LicenseValidation.swift#L347

Many users are confused because they can still read their loans even after they have returned them.

**Comment by mickael-menu** [comment]
It sounds like an incorrect server implementation. If the `rights.end` is not updated in the LCP license, that means that you could still open the book when switching off Internet, since we wouldn't be able to check the status document.

Besides, [the LSD spec says](https://readium.org/lcp-specs/releases/lsd/latest.html#32-checking-the-status-of-a-license):

> If the `status` value of a Status Document contradicts the corresponding up-to-date License Document, the License Document takes precedence.

@llemeurfr Maybe something to add to the server certification?

**Comment by mickael-menu** [comment]
Although [the spec doesn't mention](https://readium.org/lcp-specs/releases/lsd/latest.html#34-returning-a-publication) that `rights.end` must be updated, there's only this:

> The server MUST update the timestamp of both License and Status Document contained in the `status` and `license` keys of the `updated` object.

(cc @HadrienGardeur)

**Comment by llemeurfr** [comment]
I discussed that with the provider of this license and @mickael-menu's analysis is good. We agreed that this is something we need to check carefully (the automatic testing scripts does not test this point explicitly so far). Also we should add something in the spec; but the clear separation between the LCP and License Status Document spec makes it a bit complex.

**Comment by mickael-menu** [comment]
Thanks, I'm closing this issue since there's nothing we can do in the mobile toolkits.
