### ISSUE TITLE
LCP: if offline, detection should be quick

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-lcp-swift#25]
Currently, if the device is offline (e.g. plane mode), there is a timeout before the ebook is opened.

The detection of the offline state should be better, via the iOS API.

**Comment by mmenu-mantano** [comment]
Is it still an issue?
I didn't notice any delay when opening an LCP-protected book on an offline device.

**Comment by mmenu-mantano** [comment]
I'm closing this as I don't have this problem. But feel free to open it again if necessary, because I didn't have this issue before the LCP refactoring either.
