### ISSUE TITLE
Merge r2-lcp-wrapper-swift into r2-lcp-swift

### ISSUE THREAD

**Issue by mmenu-mantano** [readium/r2-lcp-swift#28]
There is an additional project (r2-lcp-wrapper-swift) containing the Objective-C++ / Swift wrapper around the liblcp static lib.

We should be able to put this wrapper directly into r2-lcp-swift to simplify the repos and align with the Kotlin implementation (which doesn't rely on r2-lcp-wrapper-kotlin)

**Comment by llemeurfr** [comment]
If this is technically possible I approve that.

**Comment by mmenu-mantano** [comment]
The wrapper will eventually be private and build a `.framework` to have a similar solution to the `.aar` on Kotlin.
