### ISSUE TITLE
infinite spinner on certain protected epub files

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-lcp-swift#59]
I've been sent an epub file which has a known flaw = the cover is encrypted. 

The R2 Reader iOS does not crash but doesn't display any page. All pages are blank with an infinite spinner. Wondering if the encrypted cover can provoque this. I see no such issue with R2 Reader Android on the same file (only the cover is blank). 

I can provide the file.

**Comment by aferditamuriqi** [comment]
This was due to wrong namespace. we should add an error if required namespaces are incorrect instead of opening the publication with the spinner.

**Comment by mickael-menu** [comment]
The namespace for `Compression` in `encryption.xml` is `http://idpf.org/ns/encryption#compression` instead of the expected `http://www.idpf.org/2016/encryption#compression`. So the encryption metadata are not properly parsed.

**Comment by mickael-menu** [comment]
`Compression` is optional [per the spec](https://www.w3.org/publishing/epub3/epub-ocf.html#sec-container-metainf-encryption.xml):

> OPTIONAL child of EncryptionProperty.

So there's really no easy way to handle this, because their `encription.xml` is technically valid, but doesn't reflect the contents of the publication.
