### ISSUE TITLE
LCPDF forever loading

### ISSUE THREAD

**Issue by cNille** [readium/r2-lcp-swift#74]
Hi!

I am trying out the PDF feature in readium and am not getting it to work. I've successfully imported the publication and get the extension `.lcpdf` in the suggestedFilename.

I've tried with both an epub-license and a pdf license. It works with the EPUB publication, but when opening the pdf-ebook it never stops loading. I don't see any error message in the console log.

## My code for parsing the publications:
```
do {
    print("LOCATION TYPE:", location.type, " - path: ", location.absolutePath)
    guard let (pubBox, parsingCallback) = try Publication.parse(at: URL(fileURLWithPath: location.absolutePath)) else {
         return completion(nil)
     }
     
     let (publication, container ) = pubBox
     let customIdentifier = NSURL(fileURLWithPath: location.absolutePath).deletingPathExtension?.lastPathComponent
     publication.metadata.otherMetadata["id"] = customIdentifier
     self.items[customIdentifier!] = (container, parsingCallback)

     try self.publicationServer!.add(publication, with: container)
     completion(publication)
} catch {
    ...
}
```

## Dependencies

App's `Cartfile.resolved`:
```
github "cezheng/Fuzi" "3.1.1"
github "dexman/Minizip" "1.4.0"
github "edrlab/GCDWebServer" "3.6.2"
github "jdg/MBProgressHUD" "1.1.0"
github "krzyzanowskim/CryptoSwift" "1.2.0"
github "onevcat/Kingfisher" "5.9.0"
github "readium/r2-navigator-swift" "1.2.6"
github "readium/r2-shared-swift" "1.4.3"
github "readium/r2-streamer-swift" "1.2.5"
github "readium/readium-opds-swift" "1.2.3"
github "stephencelis/SQLite.swift" "0.12.2"
github "weichsel/ZIPFoundation" "0.9.9"
```

Using `r2-lcp-swift` (`1.2.3`) with a test liblcp. 
DM me (Christopher N) on slack and I'll share the lcpl license I am using :)

**Comment by mickael-menu** [comment]
Are you up to date with `develop`? I tried your license and didn't have any issue opening the publication.
