### ISSUE TITLE
Fixing integration of the private LCP framework

### ISSUE THREAD

**Issue by mickael-menu** [readium/r2-lcp-swift#79]
To be able to integrate the private LCP framework without modifying the Cartfile of `r2-lcp-swift`, we can invert the dependency.

Right now `r2-lcp-swift` depends on `R2LCPClient`, but we can create an interface that `R2LCPClient` will implement and `r2-lcp-swift` will use. Then, reading apps can provide the concrete implementation when calling `R2MakeLCPService(client: R2LCPClient())`

@aferditamuriqi Can the private framework depend on `r2-lcp-swift`, or we have to put this interface in `r2-shared-swift`?

**Comment by aferditamuriqi** [comment]
The private framework should not really depend on anything more than it already is, the way the private framework is set up, it could be used without the r2-lcp-kotlin, if someone decided to write their own implementation, if we make it dependent, we close down to use it only one way (at least that's what i would understand)

also, it would cause a lot more maintenance and redistribution of the custom generated private framework.

**Comment by mickael-menu** [comment]
My issue is about the Swift version, not the Kotlin one.

If there's a need to keep it independent of `r2-lcp-swift`, then we can add the interface in `r2-shared-swift`. Right now integrators need to modify the `Cartfile` of `r2-lcp-swift` to be able to compile the app, which is not right since it's part of our repos.

**Comment by aferditamuriqi** [comment]
yes I know, I understand that it is about Swift.

**Comment by aferditamuriqi** [comment]
just to make sure, both for swift and for kotlin the private frameworks and libraries have a manual process of being generated, and I would like to avoid having any more dependencies then we already have. keep the Lcp Client independent of R2 specific dependencies.

**Comment by mickael-menu** [comment]
An alternative solution could be to have the reading apps implement the interface exposed by `r2-lcp-swift`, using the private framework. We could provide an example implementation for this in `r2-testapp-swift`. It may be the easiest solution and it doesn't require re-generating the private frameworks, but it adds more code in the reading apps that is out of our reach. The implementation should be short and easy though (it's just an adapter), so maybe it's enough.

**Comment by mickael-menu** [comment]
I implemented my last suggestion: https://github.com/readium/r2-lcp-swift/pull/112

> An alternative solution could be to have the reading apps implement the interface exposed by r2-lcp-swift, using the private framework. We could provide an example implementation for this in r2-testapp-swift. It may be the easiest solution and it doesn't require re-generating the private frameworks, but it adds more code in the reading apps that is out of our reach. The implementation should be short and easy though (it's just an adapter), so maybe it's enough.

The adapter is indeed quite small:

```swift
import R2LCPClient
import ReadiumLCP

let lcpService = LCPService(client: LCPClient())

/// Facade to the private R2LCPClient.framework.
class LCPClient: ReadiumLCP.LCPClient {

    func createContext(jsonLicense: String, hashedPassphrase: String, pemCrl: String) throws -> LCPClientContext {
        return try R2LCPClient.createContext(jsonLicense: jsonLicense, hashedPassphrase: hashedPassphrase, pemCrl: pemCrl)
    }

    func decrypt(data: Data, using context: LCPClientContext) -> Data? {
        return R2LCPClient.decrypt(data: data, using: context as! DRMContext)
    }

    func findOneValidPassphrase(jsonLicense: String, hashedPassphrases: [String]) -> String? {
        return R2LCPClient.findOneValidPassphrase(jsonLicense: jsonLicense, hashedPassphrases: hashedPassphrases)
    }

}
```
