### ISSUE TITLE
Issue integrating the LCP test lib via Carthage 

### ISSUE THREAD

**Issue by llemeurfr** [readium/r2-lcp-swift#82]
This issue is an anchor for developers in need of an update of their LCP client lib, as long one cannot compile an app with Swift x.y+1 if the LCP lib has been compiled with Swift x..

Once a solution has been found, it will be announced here and the issue will be closed.

**Comment by mickael-menu** [comment]
It might actually be an issue in Carthage, and not the LCP client lib: https://github.com/Carthage/Carthage/issues/2887

At the time I'm writing this comment, the fix hasn't been released in Carthage yet.

**Comment by llemeurfr** [comment]
In case you meet this issue, just notify me + Aferdita on the Readium Slack, a version of the LCP lib corresponding to your Swift version will be delivered to work around the issue.

**Comment by aferditamuriqi** [comment]
There have been numerous issues reported on this, but I can assure the ABI modules stability is not an issue here. 

issues were caused 
- by faulty Carthage caches etc. 
- leftover use in cocoa pods
- misconfigured dependencies 
- out of date dependencies 
etc.


steps to go about this:

Clear Out Carthage’s Cache
rm -rf ~/Library/Caches/org.carthage.CarthageKit

Clear Out Cocoapods’ Cache
rm -rf "${HOME}/Library/Caches/CocoaPods"

Clear Out the Old Brews
brew cleanup

Update Carthage to the latest version 
Update Cocoapods to the latest version
Update Xcode to the latest version

if you have more questions and issues please contact us in slack

**Comment by llemeurfr** [comment]
We need someone to go though the process in a clean manner and report on how this integration can be made easy 100% of the time. This will be added to the readme of this repo.

**Comment by mickael-menu** [comment]
[Carthage just released the version 0.35.0](https://github.com/Carthage/Carthage/releases/tag/0.35.0). In the changelog, they say that they fixed the issue with the warning message:

> "Incompatible Swift version - framework was built with \(framework) and the local version is \(local)."

**Comment by mickael-menu** [comment]
Unfortunately, the issue still occurs with 0.35.0, [despite cleaning everything](https://github.com/readium/r2-lcp-swift/issues/82#issuecomment-638833472)... 

```
*** Downloading liblcp.framework binary at "1.0.4"
Incompatible Swift version - framework was built with 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53).
```

I still think it's a Carthage issue, because I managed to build properly by downloading the framework manually. Here's how to do that for anyone stuck:

1. Open the `liblcp.json` file listed in the `Cartfile`.
2. Download the link for the latest version (e.g. 1.0.4.zip).
3. Uncompress the ZIP archive, it will give you a `R2LCPClient.framework` bundle.
4. Copy it to:
   * `Carthage/Build/iOS/R2LCPClient.framework`
   * `r2-lcp-swift/Carthage/Build/iOS/R2LCPClient.framework`

**Comment by llemeurfr** [comment]
The issue is now solved with a new version of the LCP lib. Please contact EDRLab for getting instructions. 

I'll close this issue for now, it may be re-opened if further issues arise.
