### ISSUE TITLE
Issues decrypting LCP resources (CBCDRMInputStream)

### ISSUE THREAD

**Issue by mickael-menu-mantano** [readium/r2-lcp-swift#92]
`CBCDRMInputStream` needs to be reviewed because there are a number of issues:

- @aferditamuriqi  found out last July an issue with extra padding in non-deflated resources (which are decrypted with `CBCDRMInputStream`).
- When calculating the `positionList` of a LCPDF, we have to read the `CBCDRMInputStream` entirely into a `Data` buffer, otherwise random access doesn't work:
https://github.com/readium/r2-streamer-swift/blob/1de6db2cf5c72e88384d238454a6fd8b9746022f/r2-streamer-swift/Parser/PDF/PDFParser.swift#L193-L197

A few clues:
- @danielweck left [a comment on a code review](https://github.com/readium/r2-streamer-swift/commit/6f95ad43044a199c6580570e3fe68bc8108ccbd2#r34414670) that might be related to this issue.
- @aferditamuriqi made a quick fix that only applies to HTML resources to remove the padding. However, this should not depend on the content-type, but unfortunately she encountered issues with fonts if applied all the time: https://github.com/readium/r2-streamer-swift/blob/1de6db2cf5c72e88384d238454a6fd8b9746022f/r2-streamer-swift/Fetcher/DRM/CBCDRMInputStream.swift#L120-L124
- I jotted a few notes down, regarding the fonts issue when removing the padding:
  - [This function](https://github.com/readium/r2-streamer-swift/blob/0650f6ee508a6012dc31990e43221a87c6c56e3f/r2-streamer-swift/Fetcher/DRM/CBCDRMInputStream.swift#L132) is called for each range of data, so when removing the last byte, it is removed from each chunk instead of only at the end of the resource.
  - If a resource [is bigger than a certain buffer size](https://github.com/readium/r2-streamer-swift/blob/e4b720cb234081168314d5a106365673336074ec/r2-streamer-swift/Server/WebServerResourceResponse.swift#L138), then we split the read in several chunks. This usually doesn't happen for HTML because it's so small, but I noticed that fonts are usually read in 2 or more chunks.
  - It should have been enough to reduce the reported stream size in `plainTextSize` instead, but [it's supposed to be done already](https://github.com/readium/r2-streamer-swift/blob/0650f6ee508a6012dc31990e43221a87c6c56e3f/r2-streamer-swift/Fetcher/DRM/CBCDRMInputStream.swift#L53).
 - [`CBCDRMInputStream` was directly translated from this C++ implementation](https://github.com/readium/readium-lcp-client/blob/764b28f5f4d879f771be7e727cf4a79ac0d62d9f/src/lcp-client-lib/AesCbcSymmetricAlgorithm.cpp#L125). The only difference I can see is that [the C++ version provides the type of padding](https://github.com/readium/readium-lcp-client/blob/764b28f5f4d879f771be7e727cf4a79ac0d62d9f/src/lcp-client-lib/AesCbcSymmetricAlgorithm.cpp#L122). The private LCP framework doesn't take any padding scheme as a parameter though, so I'm not sure we're getting the proper `outSize`, which might explain why the padding could not be removed properly. Any thoughts on the padding scheme @danielweck?

**Comment by mickael-menu** [comment]
Equivalent issue on r2-lcp-kotlin: https://github.com/readium/r2-lcp-kotlin/issues/81

And a Kotlin PR fixing it: https://github.com/readium/r2-lcp-kotlin/pull/84
